[tool.poetry]
name = "c4-discord-bot"
version = "0.1.0"
description = ""
authors = ["Luna <itsactuallyluna9@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
discord-py = "^2.4.0"
httpx = "^0.28.1"
python-dotenv = "^1.0.1"
apscheduler = "^3.11.0"
pillow = "^11.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
